### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mmadrid509** [NathanWolf/Bukkit-Unit-Tests#1]
Hey, so I was looking around for a custom crafting plugin that works with geyser, and I found my way here. Is this idea still here?

**Comment by NathanWolf** [comment]
Well you ended up in a strange place, but you almost made it XD

https://github.com/elBukkit/MagicPlugin

Yes my plugin Magic can do custom crafting that works with Geyser. Custom item ingredients don’t work super well though, nor in Java, due to client issues with the knowledge book, but crafting itself does work fine.

**Comment by mmadrid509** [comment]
so the plugin itself works with geyser too?

**Comment by mmadrid509** [comment]
@NathanWolf

**Comment by NathanWolf** [comment]
Yes.
